Final/picUnionTest/Controllers/WorkSpaceController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using 期末專題_圖片平台.Models;

namespace 期末專題_圖片平台.Controllers
{
    public class WorkSpaceController : Controller
    {
        CWorkSpace_Factory factory = new CWorkSpace_Factory();

        // GET: WorkSpace
        public ActionResult Index()
        {
            CWorkSpace_Factory factory = new CWorkSpace_Factory();
            return View(factory.wGet所有作品());
        }
        
        public ActionResult w新增作品()
        {
            return View();
        }
        //[HttpPost]
        //public ActionResult w新增作品(HttpPostedFileBase 圖片檔案, CWorkSpace w)
        //{
        //    string fileName = "";
        //    string filePath = "";
        //    if (圖片檔案 != null)
        //    {
        //        if (圖片檔案.ContentLength > 0)
        //        {
        //            fileName = Path.GetFileName(圖片檔案.FileName);
        //            var fileExtension = Path.GetExtension(圖片檔案.FileName);
        //            var fileWithoutExtension = Path.GetFileNameWithoutExtension(圖片檔案.FileName);
        //            filePath = Path.Combine(Server.MapPath("~/Upload_image"),圖片檔案.FileName);
        //            圖片檔案.SaveAs(filePath);
                    
        //            w.圖片名稱 = fileName;
        //            w.圖片路徑 = "~/Upload_image/" + 圖片檔案.FileName;
        //            w.上傳日期 = (new CWorkSpace_Factory()).w上傳時間();
        //            if (string.IsNullOrEmpty(w.姓名))
        //                w.姓名 = "未填寫";
        //            if (string.IsNullOrEmpty(w.作品名稱))
        //                w.作品名稱 = "未填寫";
        //            if (string.IsNullOrEmpty(w.作品描述))
        //                w.作品描述 = "未填寫";
        //            if (string.IsNullOrEmpty(w.分類))
        //                w.分類 = "未填寫";
        //            if (string.IsNullOrEmpty(w.勾選項目分類))
        //                w.勾選項目分類 = "未填寫";
        //            (new CWorkSpace_Factory()).w新增作品(w);
        //        }
        //    }
        //    return RedirectToAction("Index");
        //}
        public ActionResult w瀏覽作品()
        {
            return View(factory.wGet所有作品());
        }
        public ActionResult w我的作品(string name)
        {
            return View(factory.wGetBy姓名(name));
        }
        public ActionResult w搜尋我的作品(string keyword)
        {
            return View(factory.wGetBy關鍵字(keyword));
        }

        public ActionResult w搜尋作品(string keyword)
        {
            return View(factory.wGetBy關鍵字(keyword));
        }
        [HttpGet]
        public ActionResult w修改作品資料(int id)
        {
            CWorkSpace myWork = (new CWorkSpace_Factory()).wGetBy編號(id);
            if(myWork == null)
            {
                return RedirectToAction("Index");
            }
            return View(myWork);
        }

        [HttpPost]
        public ActionResult w新增作品(HttpPostedFileBase 圖片檔案, CWorkSpace w)
        {
            string fileName = "";
            string filePath = "";
            if (圖片檔案 != null)
            {
                if (圖片檔案.ContentLength > 0)
                {
                    fileName = Path.GetFileName(圖片檔案.FileName);
                    var fileExtension = Path.GetExtension(圖片檔案.FileName);
                    var fileWithoutExtension = Path.GetFileNameWithoutExtension(圖片檔案.FileName);
                    filePath = Path.Combine(Server.MapPath("~/Upload_image"), 圖片檔案.FileName);
                    圖片檔案.SaveAs(filePath);


                    w.圖片名稱 = fileName;

                    //回覆訊息

                    byte[] imgData;

                    using (var reader = new BinaryReader(圖片檔案.InputStream))
                    {
                        imgData = reader.ReadBytes(圖片檔案.ContentLength);
                    }

                    //var bytes = ImageToByte2(圖片檔案);
                    var ImgurRet = UploadImage2Imgur(imgData);

                    /////
                    /////

                    w.圖片路徑 = (new Uri(""+ ImgurRet.data.link).ToString());

                    //w.圖片路徑 = "";
                    w.上傳日期 = (new CWorkSpace_Factory()).w上傳時間();
                    if (string.IsNullOrEmpty(w.姓名))
                        w.姓名 = "未填寫";
                    if (string.IsNullOrEmpty(w.作品名稱))
                        w.作品名稱 = "未填寫";
                    if (string.IsNullOrEmpty(w.作品描述))
                        w.作品描述 = "未填寫";
                    if (string.IsNullOrEmpty(w.分類))
                        w.分類 = "未填寫";
                    if (string.IsNullOrEmpty(w.勾選項目分類))
                        w.勾選項目分類 = "未填寫";
                    (new CWorkSpace_Factory()).w新增作品(w);
                }
            }
            return RedirectToAction("w新增作品");
        }

        static dynamic UploadImage2Imgur(byte[] image)
        {
            HttpClient client = new HttpClient();
            string uriBase = "https://api.imgur.com/3/upload";

            // Request headers.
            client.DefaultRequestHeaders.Add(
                "Authorization", $"Client-ID 317c12e82db1240");

            string uri = uriBase;

            HttpResponseMessage response;

            // Add the byte array as an octet stream to the request body.
            using (ByteArrayContent content = new ByteArrayContent(image))
            {
                // This example uses the "application/octet-stream" content type.
                // The other content types you can use are "application/json"
                // and "multipart/form-data".
                content.Headers.ContentType =
                    new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");

                // Asynchronously call the REST API method.
                response = client.PostAsync(uri, content).Result;
            }

            // Asynchronously get the JSON response.
            string JSON = response.Content.ReadAsStringAsync().Result;

            return Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(JSON);
        }

        static byte[] ImageToByte2(Image img)
        {
            using (var stream = new System.IO.MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }



        //[HttpPost]
        //public ActionResult w修改作品資料(HttpPostedFileBase 圖片檔案, CWorkSpace w ,int id)
        //{
        //    CWorkSpace_Factory factory = new CWorkSpace_Factory();
        //    if (圖片檔案 != null)
        //    {
        //        if (圖片檔案.ContentLength > 0)
        //        {
        //            var fileName = Path.GetFileName(圖片檔案.FileName);
        //            var fileExtension = Path.GetExtension(圖片檔案.FileName);
        //            var fileWithoutExtension = Path.GetFileNameWithoutExtension(圖片檔案.FileName);
        //            var filePath = Path.Combine(Server.MapPath("~/Upload_image"), 圖片檔案.FileName);
        //            圖片檔案.SaveAs(filePath);

        //            w.圖片名稱 = fileName;
        //            w.圖片路徑 = "~/Upload_image/"+圖片檔案.FileName;
        //            w.上傳日期 = (new CWorkSpace_Factory()).w上傳時間();

        //            factory.w修改作品資料(w, id);
        //        }
        //    }

        //    return RedirectToAction("Index");
        //}


        public ActionResult w刪除作品(int id)
        {
            CWorkSpace_Factory factory = new CWorkSpace_Factory();
            factory.w刪除作品By編號(id);
            return RedirectToAction("Index");
        }
    }
}

Final/picUnionTest/Views/WorkSpace/Index.cshtml
@model 期末專題_圖片平台.Models.CWorkSpace[]
@using 期末專題_圖片平台.Models
@{
    ViewBag.Title = "wWorkPage";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>作品管理</title>
    <link href="~/Content/css/Basic.css" rel="stylesheet" />
    <link href="~/Content/css/artistphoto.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
    <figure class="all">
        <h3>作品管理</h3>
        <a href="~/WorkSpace/w新增作品">新增作品</a>
        <input type="text" id="search" name="keyword" />
        <div class="btn">
            <span>@Html.ActionLink("搜尋", "w搜尋我的作品", "WorkSpace", new { keyword = "x" }, new { @Class = "link" })</span>@*set actionlink htmlattribute==>class*@
        </div>
        <div class="bt1" style="text-align:center;">
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=lotus"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">lotus</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=flowerminimalist"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">flowerminimalist</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=mandala"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">mandala</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=wrist"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">wrist</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=Watercolor"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">Watercolor</span></a>
        </div>
        <figcaption>作品預覽</figcaption>
        <div id="container" class="pic">
            @{
                foreach (CWorkSpace w in Model)
                {
                    <div id="mywork:@w.編號" class="picin">
                        <a href="~/WorkSpace/w修改作品資料/?id=@w.編號"><img src="@Url.Content(w.圖片路徑)" title="@w.圖片名稱" /></a>
                    </div>
                }
            }
        </div>
    </figure>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/jsFunction/search_replace.js"></script>
</body>
</html>

Final/picUnionTest/Views/WorkSpace/w修改作品資料.cshtml
@model 期末專題_圖片平台.Models.CWorkSpace
@{
    ViewBag.Title = "w修改作品資料";
}

<html>
<head>
    <meta charset="utf-8" />
    <title>修改作品資料</title>
    <link href="~/Content/css/Basic.css" rel="stylesheet" />
    <link href="~/Content/css/photoDetail.css" rel="stylesheet" />
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        <figure class="all">
            <h3>作品編輯</h3><br />
            <figcaption>預覽</figcaption>
            <img id="show_img" src="~/Upload_image/@Model.圖片名稱" alt="選擇的圖片" />
            <br />
            <input id="upload_img" type="file" name="圖片檔案" required />
            <hr /><br />
            <label>作品名稱:</label>
            <br /><input type="text" name="作品名稱" value="@Model.作品名稱"/>
            <div>
                <label>作品描述:</label>
                <br />
                <textarea name="作品描述" cols="50" rows="5" style="resize:none" >@Model.作品描述</textarea>
            </div>
            <div>
                <label>作品類別:</label>
                <br /><input id="txtCate" type="text" name="分類" value="@Model.分類" />
            </div>
            <div>
                <input id="txtCheckBoxCate" type="hidden" name="勾選項目分類" value="@Model.勾選項目分類" />
            </div>
            <div class="cblabel">
                <input type="checkbox" class="txtinput" value="lotus" />
                <label>lotus</label>
                <input type="checkbox" class="txtinput" value="Ink" />
                <label>Ink</label>
                <input type="checkbox" class="txtinput" value="flowerminimalist" />
                <label>flowerminimalist</label>

                <input type="checkbox" class="txtinput" value="tattoohalf" />
                <label>tattoohalf</label>
                <input type="checkbox" class="txtinput" value="sleeve" />
                <label>sleeve</label>
                <input type="checkbox" class="txtinput" value="mandala" />
                <label>mandala</label>

                <input type="checkbox" class="txtinput" value="wrist" />
                <label>wrist</label>
                <input type="checkbox" class="txtinput" value="arm" />
                <label>arm</label>

            </div>

            <div class="btn">
                <input type="submit" id="btnSubmit2" value="修改" onclick="categoryCheckBox()" />
            </div>
        </figure>
    </form>
</body>
</html>
<div>
    @Html.ActionLink("回上一頁", "Index")
</div>
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jsFunction/imagePreview.js"></script>
<script src="~/Scripts/jsFunction/categoryCheckBox_wModify.js"></script>
<script src="~/Scripts/jsFunction/categoryCheckBox.js"></script>

Final/picUnionTest/Views/WorkSpace/w搜尋作品.cshtml
@model 期末專題_圖片平台.Models.CWorkSpace[]
@using 期末專題_圖片平台.Models
    @{
        ViewBag.Title = "w搜尋作品";
    }
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/masonry.pkgd.min.js"></script>
<style>
    .item {
        width: 220px;
        margin: 10px;
        float: left;
    }
</style>
<h2>搜尋作品</h2>
<div> <input type="text" id="search" name="keyword" />
      <span>@Html.ActionLink("搜尋", "w搜尋作品", "WorkSpace", new { keyword = "x" }, new { @Class = "link" })</span>@*set actionlink htmlattribute==>class*@
</div>
<div id="container">
    @{
        foreach (CWorkSpace w in Model)
        {
            <div class="item">
                <img src="@Url.Content(w.圖片路徑)" title="@w.圖片名稱" />
                <p>@w.作品描述</p>
                <span>@w.分類</span><span>作者:@w.姓名</span>
            </div>
        }
    }
</div>
<div>@Html.ActionLink("瀏覽所有圖片","w瀏覽作品")</div>

<script>
    /*jQuery replace keyword value by input value*/
    $(function(){
        $(".link").click(function(){
            var txtValue =$("#search").val();
            this.href =this.href.replace("x",txtValue);
        });
    });
</script>

Final/picUnionTest/Views/WorkSpace/w搜尋我的作品.cshtml
@model 期末專題_圖片平台.Models.CWorkSpace[]
@using 期末專題_圖片平台.Models
@{
    ViewBag.Title = "w搜尋我的作品";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>作品管理</title>
    <link href="~/Content/css/Basic.css" rel="stylesheet" />
    <link href="~/Content/css/artistphoto.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
    <figure class="all">
        <h3>作品管理</h3>
        <a href="~/WorkSpace/w新增作品">新增作品</a>
        <input type="text" id="search" name="keyword" />
        <div class="btn">
            <span>@Html.ActionLink("搜尋", "w搜尋我的作品", "WorkSpace", new { keyword = "x" }, new { @Class = "link" })</span>@*set actionlink htmlattribute==>class*@
        </div>
        <div class="bt1" style="text-align:center;">
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=lotus"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">lotus</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=flowerminimalist"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">flowerminimalist</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=mandala"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">mandala</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=wrist"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">wrist</span></a>
            <a href="~/WorkSpace/w搜尋我的作品/?keyword=Watercolor"><span class="btn btn-outline-secondary" style="margin:0 3px 0 3px;">Watercolor</span></a>
        </div>
        <figcaption>作品預覽</figcaption>
        <div id="container" class="pic">
            @{
                foreach (CWorkSpace w in Model)
                {
                    <div id="mywork:@w.編號" class="picin">
                        <a href="~/WorkSpace/w修改作品資料/?id=@w.編號"><img src="@Url.Content(w.圖片路徑)" title="@w.圖片名稱" /></a>
                    </div>
                }
            }
        </div>
    </figure>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/jsFunction/search_replace.js"></script>
</body>
</html>

Final/picUnionTest/Views/WorkSpace/w新增作品.cshtml
@{
    ViewBag.Title = "w新增作品";
}
<html>
<head>
    <meta charset="utf-8" />
    <title>新增作品</title>
    <link href="~/Content/css/Basic.css" rel="stylesheet" />
    <link href="~/Content/css/photoDetail.css" rel="stylesheet" />
</head>
<body>
    <form method="post" enctype="multipart/form-data">

        <figure class="all">
            <h3>作品編輯</h3><br />
            <figcaption>預覽</figcaption>
            <img id="show_img" src="" alt="選擇的圖片" />
            <br />
            <input id="upload_img" type="file" name="圖片檔案" required />
            <hr /><br />
            <label>作品名稱:</label>
            <br /><input type="text" name="作品名稱" />
            <div>
                <label>作品描述:</label>
                <br />
                <textarea name="作品描述" cols="50" rows="5" style="resize:none" ></textarea>
            </div>
            <div>
                <label>作品類別:</label>
                <br /><input id="txtCate" type="text" name="分類" value="" />
            </div>
            <div>
                <input id="txtCheckBoxCate" type="hidden" name="勾選項目分類" value="" />
            </div>
            <div class="cblabel">
                    <input type="checkbox" class="txtinput" value="lotus"/>
                    <label>lotus</label>
                    <input type="checkbox" class="txtinput" value="Ink"/>
                    <label>Ink</label>
                    <input type="checkbox" class="txtinput" value="flowerminimalist"/>
                    <label>flowerminimalist</label>
              
                    <input type="checkbox" class="txtinput" value="tattoohalf"/>
                    <label>tattoohalf</label>
                    <input type="checkbox" class="txtinput" value="sleeve"/>
                    <label>sleeve</label>
                    <input type="checkbox" class="txtinput" value="mandala"/>
                    <label>mandala</label>
              
                    <input type="checkbox" class="txtinput" value="wrist"/>
                    <label>wrist</label>
                    <input type="checkbox" class="txtinput" value="arm"/>
                    <label>arm</label>
               
            </div>

            <div class="btn">
                <input type="submit" id="btnSubmit2" value="送出" onclick="categoryCheckBox()"/>
            </div>
        </figure>
    </form>
</body>
</html>
<div>
    @Html.ActionLink("回上一頁", "w搜尋我的作品")
</div>
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jsFunction/imagePreview.js"></script>
<script src="~/Scripts/jsFunction/categoryCheckBox.js"></script>

Final/picUnionTest/Views/WorkSpace/w瀏覽作品.cshtml
@model 期末專題_圖片平台.Models.CWorkSpace[]
@using 期末專題_圖片平台.Models

@{
    ViewBag.Title = "w瀏覽作品";
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/masonry.pkgd.min.js"></script>
<style>
    .item{
        width:220px;
        margin:10px;
        float:left;
    }
    .item img{
        width:400px;

    }
</style>
<h2>瀏覽作品</h2>
<div> <input type="text" id="search" name="search" /><span>@Html.ActionLink("搜尋", "w搜尋作品", "WorkSpace",new { keyword ="x" },new { @Class = "link" })</span></div>@*set actionlink htmlattribute==>class*@
<div id="container">
    @{ 
        foreach (CWorkSpace w in Model)
        {
            <div class="item">
                <img src="@Url.Content(w.圖片路徑)" title="@w.圖片名稱"/>
                <p>作品描述: @w.作品描述</p>
                <span> 分類: @w.分類 </span><span> 作者: @w.姓名</span>
            </div>
            }
    }
</div>
<script>
    /*jQuery replace keyword value by input value*/
    $(function(){
        $(".link").click(function(){
            var txtValue =$("#search").val();
            this.href =this.href.replace("x",txtValue);
        });
    });
</script>